In [10]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [19]:
import pandas as pd
data = {
    "Car": ["Honda City","Hyundai Creta","Maruti Swift","Tata Nexon","Toyota Innova","Honda Amaze","Kia Seltos","Maruti Baleno"],
    "Company": ["Honda","Hyundai","Maruti","Tata","Toyota","Honda","Kia","Maruti"],
    "Year": [2022,2023,2021,2023,2022,2020,2024,2021],
    "Price": [1200000,1500000,700000,1100000,2200000,650000,1600000,800000],
    "Fuel": ["Petrol","Diesel","Petrol","Diesel","Diesel","Petrol","Petrol","Petrol"],
    "Mileage": [18,17,23,19,14,20,16,22],
    "Rating": [4.5,4.3,4.2,4.4,4.6,4.0,4.5,4.1]
}
df = pd.DataFrame(data)
df

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
2   Maruti Swift   Maruti  2021   700000  Petrol       23     4.2
3     Tata Nexon     Tata  2023  1100000  Diesel       19     4.4
4  Toyota Innova   Toyota  2022  2200000  Diesel       14     4.6
5    Honda Amaze    Honda  2020   650000  Petrol       20     4.0
6     Kia Seltos      Kia  2024  1600000  Petrol       16     4.5
7  Maruti Baleno   Maruti  2021   800000  Petrol       22     4.1

In [20]:
df.head()

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
2   Maruti Swift   Maruti  2021   700000  Petrol       23     4.2
3     Tata Nexon     Tata  2023  1100000  Diesel       19     4.4
4  Toyota Innova   Toyota  2022  2200000  Diesel       14     4.6

In [21]:
df.tail()

             Car Company  Year    Price    Fuel  Mileage  Rating
3     Tata Nexon    Tata  2023  1100000  Diesel       19     4.4
4  Toyota Innova  Toyota  2022  2200000  Diesel       14     4.6
5    Honda Amaze   Honda  2020   650000  Petrol       20     4.0
6     Kia Seltos     Kia  2024  1600000  Petrol       16     4.5
7  Maruti Baleno  Maruti  2021   800000  Petrol       22     4.1

In [22]:
df.shape

(8, 7)

In [23]:
df.columns

Index(['Car', 'Company', 'Year', 'Price', 'Fuel', 'Mileage', 'Rating'], dtype='object')

In [24]:
df.dtypes

Car         object
Company     object
Year         int64
Price        int64
Fuel        object
Mileage      int64
Rating     float64
dtype: object

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Car      8 non-null      object
 1   Company  8 non-null      object
 2   Year     8 non-null      int64
 3   Price    8 non-null      int64
 4   Fuel     8 non-null      object
 5   Mileage  8 non-null      int64
 6   Rating   8 non-null      float64
dtypes: float64(1), int64(3), object(3)
memory usage: 580.0+ bytes

In [31]:
df["Car"]

0       Honda City
1    Hyundai Creta
2     Maruti Swift
3       Tata Nexon
4    Toyota Innova
5      Honda Amaze
6       Kia Seltos
7    Maruti Baleno
Name: Car, dtype: object

In [26]:
df[["Car","Price"]]

             Car    Price
0     Honda City  1200000
1  Hyundai Creta  1500000
2   Maruti Swift   700000
3     Tata Nexon  1100000
4  Toyota Innova  2200000
5    Honda Amaze   650000
6     Kia Seltos  1600000
7  Maruti Baleno   800000

In [27]:
df.iloc[0:3]

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
2   Maruti Swift   Maruti  2021   700000  Petrol       23     4.2

In [32]:
df.loc[0:1]

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3

In [33]:
from numpy import e
expensive_cars = df[df["Price"] > 1000000]
print(expensive_cars)

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
3     Tata Nexon     Tata  2023  1100000  Diesel       19     4.4
4  Toyota Innova   Toyota  2022  2200000  Diesel       14     4.6
6     Kia Seltos      Kia  2024  1600000  Petrol       16     4.5

In [34]:
sorted_cars = df.sort_values(by="Price")

In [35]:
print(sorted_cars)

             Car  Company  Year    Price    Fuel  Mileage  Rating
5    Honda Amaze    Honda  2020   650000  Petrol       20     4.0
2   Maruti Swift   Maruti  2021   700000  Petrol       23     4.2
7  Maruti Baleno   Maruti  2021   800000  Petrol       22     4.1
3     Tata Nexon     Tata  2023  1100000  Diesel       19     4.4
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
6     Kia Seltos      Kia  2024  1600000  Petrol       16     4.5
4  Toyota Innova   Toyota  2022  2200000  Diesel       14     4.6

In [36]:
avg_price = df["Price"].mean()
print(avg_price)

1218750.0

In [40]:
print("Highest Price", df["Price"].max())
print("Lowest Price", df["Price"].min())

Highest Price 2200000
Lowest Price 650000

In [41]:
df.describe(

)

              Year         Price    Mileage    Rating
count     8.000000  8.000000e+00   8.000000  8.000000
mean   2022.000000  1.218750e+06  18.625000  4.325000
std       1.309307  5.304563e+05   3.020761  0.212132
min    2020.000000  6.500000e+05  14.000000  4.000000
25%    2021.000000  7.750000e+05  16.750000  4.175000
50%    2022.000000  1.150000e+06  18.500000  4.350000
75%    2023.000000  1.525000e+06  20.500000  4.500000
max    2024.000000  2.200000e+06  23.000000  4.600000

In [42]:
print(df["Company"].value_counts())

Company
Honda      2
Maruti     2
Hyundai    1
Tata       1
Toyota     1
Kia        1
Name: count, dtype: int64

In [43]:
print(df["Fuel"].unique())

['Petrol' 'Diesel']

In [44]:
df.isnull().sum()

Car        0
Company    0
Year       0
Price      0
Fuel       0
Mileage    0
Rating     0
dtype: int64

In [49]:
sample = pd.DataFrame({
    "Cars": ["Honda","Tata","Hyundai","Maruti"],
    "Price": [1200000,None,1500000,700000],
    "Mileage": [18,17,None,19]
})
print(sample)

      Cars      Price  Mileage
0    Honda  1200000.0     18.0
1     Tata        NaN     17.0
2  Hyundai  1500000.0      NaN
3   Maruti   700000.0     19.0

In [50]:
sample["Price"] = sample["Price"].fillna(sample["Price"].mean())

sample["Mileage"] = sample["Mileage"].fillna(sample["Mileage"].mean())
print(sample)

      Cars         Price  Mileage
0    Honda  1.200000e+06     18.0
1     Tata  1.133333e+06     17.0
2  Hyundai  1.500000e+06     18.0
3   Maruti  7.000000e+05     19.0

In [53]:
df = df.drop_duplicates()
df

             Car  Company  Year    Price    Fuel  Mileage  Rating
0     Honda City    Honda  2022  1200000  Petrol       18     4.5
1  Hyundai Creta  Hyundai  2023  1500000  Diesel       17     4.3
2   Maruti Swift   Maruti  2021   700000  Petrol       23     4.2
3     Tata Nexon     Tata  2023  1100000  Diesel       19     4.4
4  Toyota Innova   Toyota  2022  2200000  Diesel       14     4.6
5    Honda Amaze    Honda  2020   650000  Petrol       20     4.0
6     Kia Seltos      Kia  2024  1600000  Petrol       16     4.5
7  Maruti Baleno   Maruti  2021   800000  Petrol       22     4.1